<?php

/**
 * PluginTagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTag');
    }
}