Tag:
  options:
    charset: utf8
    collate: utf8_bin
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    foreign_id:
      type: integer(4)
      notnull: true
    foreign_table:
      type: char(1)
      notnull: true
    tag_id:
      type: integer(4)
      notnull: true
  indexes:
    foreign_id_foreign_table_foreign_id_UNIQUE:
      fields: [foreign_id, foreign_table, tag_id]
      type: unique
