Tag:
  options:
    charset: utf8
    collate: utf8_bin
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    entity:
      type: string(12)
      notnull: true
    tag:
      type: string(16)
      notnull: true
  indexes:
    entity_tag_UNIQUE:
      fields: [entity,tag]
      type: unique
